---
# Note: The following configuration is only for development purpose.
# Do not use the same configuration in production!
services:
  database:
    image: docker.io/library/postgres:16.2-alpine
    ## Note: The default PostgreSQL published container port on the host is 5432.
    ## You can change it to another port.
    ports:
      - "127.0.0.1:5432:5432/tcp"
    environment:
      POSTGRES_USER: exercise
      POSTGRES_PASSWORD: JLCHaWtXsC5q7YKC
      POSTGRES_DB: exercise
    volumes:
      - "database_data:/var/lib/postgresql/data"
  pgadmin:
    image: docker.io/dpage/pgadmin4:8.4
    ## Note: Use `docker ps` output to get the published port for the pgadmin instance.
    ports:
      - "80/tcp"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80

volumes:
  database_data:
